/**
 * What `@lyteboat/distro` publishes: the dsh release the kernel was imported from
 * and the kernel extensions this build carries. Generated by
 * scripts/dist/gen-distro-manifest.ts from dsh-compat/contract/extensions.yml and
 * dsh.upstream.json; do not edit, rerun the script after changing either file.
 * @module @lyteboat/distro/distro-manifest
 */

import type { LyteboatDistroExtension } from '@lyteboat/contracts'

/** The dsh release the kernel was imported from. */
export const DSH_BASE = '0.2.0-rc.2'

/** Every kernel extension this build carries. */
export const DISTRO_EXTENSIONS: readonly LyteboatDistroExtension[] = Object.freeze([
  { id: 'agent-loop-intake', package: '@deepseek-ai/dsh-agent-loop', kind: 'event' },
  { id: 'agent-loop-pre-assemble', package: '@deepseek-ai/dsh-agent-loop', kind: 'event' },
  { id: 'session-append-ignorable', package: '@deepseek-ai/dsh-session', kind: 'api-option' },
  { id: 'session-controller-prompt-source', package: '@deepseek-ai/dsh-api-session-controller', kind: 'api-option' },
])
